### PR TITLE
scriptlet/01-alternatives.sh: bugfix and enhancements

### LINKED ISSUE #136: scriptlet/alternative.sh defunct in 1.6.64
Code introduced in commit 5ef4a89 introduced a bug, making alternative does not work as expected.

https://github.com/AOSC-Dev/autobuild3/blob/3a43261406bc271a664a45172a7585a26bcbd91f/scriptlet/01-alternatives.sh#L16-L28

### PR DESCRIPTION
**Pull request by CamberLoid**
* Fixes #136
* Now supports group-specific alternatives file, like arch_loadvar() in lib/arch.sh
* More abinfo/abdbg outputs!

### CODE REVIEW

**Comment by CamberLoid** [comment]
Can personally testify that this fixes issue #136 , and enhancements work in expectation.

File: scriptlet/01-alternatives.sh [hunk 1]
```diff
@@ -13,18 +13,45 @@ addalt(){
...
 alternative(){ while (($#)); do addalt "$1" "$(basename "$1")" "$2" "$3"; shift 3 || break; done; }
 
+_hasAlternative=0
+
+if [ -e "$SRCDIR"/autobuild/alternatives ]; then
+	abdbg "Found common alternatives file: ${SRCDIR}/autobuild/alternatives"
+	_hasAlternative=1
+fi
+
+## ${CROSS:-$ARCH} or $ABHOST is always prior than arch groups
```
Comment (cthbleachbit) [inline scriptlet/01-alternatives.sh:23]: Nit: "More specific per-arch alternatives file always take precedence over per-group ones"

File: scriptlet/01-alternatives.sh [hunk 2]
```diff
@@ -13,18 +13,45 @@ addalt(){
 # alternative path link prio [path2 link2 prio2 ..]
 alternative(){ while (($#)); do addalt "$1" "$(basename "$1")" "$2" "$3"; shift 3 || break; done; }
 
+_hasAlternative=0
+
+if [ -e "$SRCDIR"/autobuild/alternatives ]; then
```
Comment (cthbleachbit) [inline scriptlet/01-alternatives.sh:18]: Potential correctness issue: Use `[ -f blah ]` instead to check for regular file. Ditto on line 24 and 30.

File: scriptlet/01-alternatives.sh [hunk 3]
```diff
@@ -13,18 +13,45 @@ addalt(){
...
+## ${CROSS:-$ARCH} or $ABHOST is always prior than arch groups
 if [ -e "$SRCDIR"/autobuild/${CROSS:-$ARCH}/alternatives ]; then
+	abdbg "Found arch-specific alternatives file: ${SRCDIR}/autobuild/${CROSS:-$ARCH}/alternatives"
+	_hasAlternative=1
+	_archTarget="/${CROSS:-$ARCH}"
+else
+	for _grp in ${ABHOST_GROUP}; do
+		if [ -e "$SRCDIR"/autobuild/${_grp}/alternatives ]; then
+			if [ $_assignedGroup ]; then
+				aberr "Refusing to treat autobuild/${_grp}/alternatives as the group-specific alternative file"
```
Comment (cthbleachbit) [inline scriptlet/01-alternatives.sh:32]: Text flow nit: `Refusing to use autobuild/${_grp}/alternatives for group-specific alternatives`

File: scriptlet/01-alternatives.sh [hunk 4]
```diff
@@ -13,18 +13,45 @@ addalt(){
...
+				aberr "... because there is another file: autobuild/${_assignedGroup}/alternatives"
+				abinfo "Current ABHOST ${ABHOST} belongs to the following groups:"
+				abinfo "${ABHOST_GROUP//$'\n'/, }"
+				abinfo "Create autobuild/${CROSS:-$ARCH}/alternatives instead to suppress the conflict"
```
Comment (cthbleachbit) [inline scriptlet/01-alternatives.sh:36]: Nit: `Create per-arch autobuild/${CROSS:-$ARCH}/alternatives instead to resolve this conflict`

File: scriptlet/01-alternatives.sh [hunk 5]
```diff
@@ -13,18 +13,45 @@ addalt(){
...
 if [ -e "$SRCDIR"/autobuild/${CROSS:-$ARCH}/alternatives ]; then
+	abdbg "Found arch-specific alternatives file: ${SRCDIR}/autobuild/${CROSS:-$ARCH}/alternatives"
+	_hasAlternative=1
+	_archTarget="/${CROSS:-$ARCH}"
+else
+	for _grp in ${ABHOST_GROUP}; do
+		if [ -e "$SRCDIR"/autobuild/${_grp}/alternatives ]; then
+			if [ $_assignedGroup ]; then
+				aberr "Refusing to treat autobuild/${_grp}/alternatives as the group-specific alternative file"
+				aberr "... because there is another file: autobuild/${_assignedGroup}/alternatives"
```
Comment (cthbleachbit) [inline scriptlet/01-alternatives.sh:33]: `... because another file autobuild/${_assignedGroup}/alternatives is also valid for this architecture`

File: scriptlet/01-alternatives.sh [hunk 6]
```diff
@@ -13,18 +13,45 @@ addalt(){
...
+				abinfo "Current ABHOST ${ABHOST} belongs to the following groups:"
+				abinfo "${ABHOST_GROUP//$'\n'/, }"
+				abinfo "Create autobuild/${CROSS:-$ARCH}/alternatives instead to suppress the conflict"
+				abdie "Ambiguous group-specific alternative file detected! Refuse to proceed."
```
Comment (cthbleachbit) [inline scriptlet/01-alternatives.sh:37]: Nit: "Multiple per-group alternative files for this architecture found! Cannot proceed."

**Review by cthbleachbit — CHANGES_REQUESTED** [review]

**Review by cthbleachbit — APPROVED** [review]
